### ISSUE TITLE
Can't press enter in haskell interactive mode

### ISSUE THREAD

**Issue by alokedesai** [haskell/haskell-mode#876]
When I press `C-c C-l` in a haskell buffer, a haskell REPL opens successfully, but I can't press enter to evaluate a haskell expression. Any ideas what this could be? haskell-mode is the only package I have installed and I've also tried reinstalling haskell-mode and even emacs to no avail.

Here's my `.emacs` file in case you need it

```
(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)

(add-to-list 'load-path "~/structured-haskell-mode/elisp")
(require 'shm)

(add-hook 'haskell-mode-hook 'structured-haskell-mode)


(require 'haskell-interactive-mode)
(require 'haskell-process)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)

(custom-set-variables
 '(haskell-process-suggest-remove-import-lines t)
 '(haskell-process-auto-import-loaded-modules t)
   '(haskell-process-log t))
```

**Comment by gracjan** [comment]
Can you try to set to nil each of the variables in turn:

```el
'(haskell-process-suggest-remove-import-lines t)
'(haskell-process-auto-import-loaded-modules t)
'(haskell-process-log t)
```

so that only one of those is set to `t` and then report what happened?

**Comment by alokedesai** [comment]
I've tried every possible permutation of setting t to nil in these three lines and none of it worked

**Comment by gracjan** [comment]
Is there anybody else out there that has similar problem?

**Comment by alokedesai** [comment]
I've seen this [stackoverflow post](http://stackoverflow.com/questions/31220370/emacs-interactive-haskell-repl-non-response-if-either-the-cabal-or-working-direc) and another forum post somewhere that I can't remember that both describe similar problems but no fix has been described.

**Comment by gracjan** [comment]
33 upvotes and you are the first one to report the issue. Thanks for doing that. 33 people will be happy when we fix this one!

**Comment by yamafaktory** [comment]
Hi there,
I am also experiencing the same weird issue trying to play with the Haskell REPL, i.e. not being able to press enter.
I am using stack on Archlinux, Emacs 24.5.1 and here is part of my settings:

```elisp
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
(setq haskell-process-path-ghci "stack")
(custom-set-variables
 '(haskell-process-suggest-remove-import-lines t)
 '(haskell-process-auto-import-loaded-modules t)
 '(haskell-process-log t))
(define-key haskell-mode-map (kbd "C-c h") 'haskell-interactive-switch)
```

Please note that I tried @gracjan solution without any success.

Any workaround?

**Comment by PierreR** [comment]
Could you check that this is not the same issue as this one;
https://github.com/syl20bnr/spacemacs/issues/3271

**Comment by yamafaktory** [comment]
Thanks for the guidance! Unfortunately,  I am not an evil user.

**Comment by yamafaktory** [comment]
Well, I found out what the issue was.

Using M-x haskell-process-restart gave me a hint: first stack was launch with the unwanted "-ferror-spans" argument and thus I needed to provide a "ghci" argument instead:

```elisp
(setq haskell-process-path-ghci "stack")
(setq haskell-process-args-ghci '("ghci"))
```

Maybe @alokedesai you can give it a try (i.e. checking if ghci is correctly launched).

**Comment by d12frosted** [comment]
@yamafaktory what is the value of `haskell-process-type`?

**Comment by yamafaktory** [comment]
@d12frosted since then I refactored my settings, i.e. only using ```(setq haskell-process-type 'stack-ghci)``` which perfectly works.

**Comment by d12frosted** [comment]
@yamafaktory 
Yeah, that's what I wanted to suggest you, cause now (from my experience) `haskell-mode` plays nice with `stack`. Also, even if you leave `haskell-process-type` as `auto`, it should still work for projects that have `stack.yaml` file in the project root.

**Comment by d12frosted** [comment]
@alokedesai are you sure that there is space between `λ>` and what you type? I know it's silly, but it's very common problem.

**Comment by yamafaktory** [comment]
@d12frosted thanks for the guidance which should benefit other users! Maybe a stack entry or stack related instructions in the corresponding sections should be added in the wiki.

**Comment by d12frosted** [comment]
@yamafaktory you are welcome :smile: 

About the wiki, it [already](https://github.com/haskell/haskell-mode/wiki/Haskell-Interactive-Mode-Setup#ghci-process-type) says that there is `stack-ghci` process type. But it lacks some description on process types. Plus it misleads about the default value of process type. So yeah, updated it. Thanks for the call ! :smile:

**Comment by yamafaktory** [comment]
@d12frosted thanks!

**Comment by marcinmrotek** [comment]
Maybe it could help someone: on my setup (I'm using `evil`) the repl works right after `C-`` if I'm in a project that does NOT use stack; in a project with a stack.yaml, I have to `C-c C-c` before typing anything. Then pressing enter starts to work

**Comment by vimniky** [comment]
I have the same problem , I have tried a lot , but It still don't work !!!!!!

**Comment by gracjan** [comment]
Fixed by #1116.

Leave a comment if it happens again.

**Comment by ruomad** [comment]
I'm running into the same (or a similar problem).
(haskell-process-type 'stack-ghci)
When I hit C-c C-l the interactivewindow opens and displays the lambda prompt, but not the welcome message. I can type anything in the prompt but nothing happens when I press enter (and I can carry on typing).
The haskell-process-log says that everything is loaded and OK, which means stack-ghci did work properly.
I'm using the last haskell-mode from melpa.org
The strange thing is that it used to work like a week ago... and I cannot figure whathappened since then (of course I updated haskell-mode, probably)

**Comment by gracjan** [comment]
Do you have `haskell-doc-mode` enabled?

**Comment by ruomad** [comment]
I turned it off, no visible change
(remove-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)

**Comment by fice-t** [comment]
I can't really reproduce this using Cabal or Stack under normal conditions (ie. process-log clean). The most is that there's a few second delay even in a fresh Stack project where the issue temporarily occurs.

@ruomad does the problem still occur in a fresh Stack project?

**Comment by ruomad** [comment]
Humm, no it doesn't...
I'll try some tests

**Comment by ruomad** [comment]
The problem seems to be that I have a cabal project that includes both a library and executables

**Comment by ruomad** [comment]
More precisely, it seems that the problem is that I have more than one executable in the project. Works ok with stack, but prevents the REPL to open correctly.

**Comment by ruomad** [comment]
A hint could be that when I'm only building one executable, the logs show a final ^D .I get the greeting in the REPL window and I'm able to evaluate an expression by pressing ENTER.
In the contrary, when there are 2 executables, this ^D does not appear in the logs and the REPL window does not work.
The different logs are in the attached zip 
[log.zip](https://github.com/haskell/haskell-mode/files/120658/log.zip)

**Comment by ruomad** [comment]
Hereattached a better version of the logs : in the normal build, the ^D appears and then the source file is loaded, whereas in the abnormal one, the process seems to hang.
[logs.zip](https://github.com/haskell/haskell-mode/files/120665/logs.zip)

**Comment by ruomad** [comment]
Confirmed with an empty new project (stack new) modified to include 2 executables.
Furthermore, adding --main-is TARGET in haskell-process-args-stack-ghci doesn't work, whereas it works when I run stack ghci --main-is TARGET from command line
I'm using stack-1.0.2, so the change may have been in the recent stack upgrades

**Comment by ruomad** [comment]
It must somehow be related to the work done in stack-1.0.2
From changelog :
       
> GHCI: add interactive Main selection #1068

**Comment by ruomad** [comment]
The behavior is ok if I add "--no-load" to haskell-process-args-stack-ghci, but no modules are loaded except the current one

**Comment by libby** [comment]
Thanks @ruomad you helped me solve my issue! I had both stack and cabal in my emacs path. Removing cabal from the emacs path fixed the issue. By only including the stack path in the emacs `init.el` file it works as expected:

`(let ((stack-path (expand-file-name "~/.local/bin/stack")))
  (setenv "PATH" (concat stack-path path-separator (getenv "PATH")))
  (add-to-list 'exec-path stack-path))
`
